version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
        - 3333:3333
    volumes:
        - .:/usr/app
    links:
        - postgres
    depends_on:
        - postgres
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
        - POSTGRES_DB=fin_api
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=docker
        - POSTGRES_PORT=5432
        - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
        - pgdata:/data/postgres


volumes:
    pgdata:
        driver: local
